tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'github/bootstrap'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap "homebrew/formula-analytics"
tap 'homebrew/dev-tools'
tap 'homebrew/portable'
tap 'homebrew/services'
cask 'java'
brew 'ack'
brew 'autoconf'
brew 'autojump'
brew 'cmake'
brew 'xz'
brew 'libpng'
brew 'freetype'
brew 'gettext'
brew 'pcre'
brew 'git'
brew 'pkg-config'
brew 'grc'
brew 'hub'
brew 'libtool'
brew 'jpeg'
brew 'libtiff'
brew 'imagemagick'
brew 'jq'
brew 'launch_socket_server', service_restart: true
brew 'launchdns', service_restart: true
brew 'openssl'
brew 'libevent'
brew 'libgpg-error'
brew 'libgcrypt'
brew 'readline'
brew 'sqlite'
brew 'libgda'
brew 'libssh2'
brew 'libgit2'
brew 'mas'
brew 'memcached', service_restart: true
brew 'nginx', service_restart: true
brew 'ruby-build'
brew 'rbenv'
brew 'rbenv-default-gems'
brew 'nodenv'
brew 'libmcrypt'
brew 'redis', service_restart: true
brew 'shellcheck'
brew 'ssh-copy-id'
brew 'wget'
brew 'mysql'
brew 'mongodb'
brew 'thefuck'
brew "yarn", args: ["without-node"]
cask 'appcleaner'
cask 'atom'
cask 'cyberduck'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'font-source-code-pro'
cask 'google-chrome'
cask 'imagealpha'
cask 'imageoptim'
cask 'keepingyouawake'
cask 'now'
cask 'numi'
cask 'opera'
cask 'sequel-pro'
cask 'sip'
cask 'sketch'
cask 'skype-for-business'
cask 'spotify'
cask 'tyke'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
cask 'xquartz'
mas "1Password", id: 443987910
mas 'Xcode', id: 497799835
mas 'Keynote', id: 409183694
mas 'iMovie', id: 408981434
mas 'Slack', id: 803453959
mas 'Pages', id: 409201541
mas 'Pixelmator', id: 407963104
mas 'Numbers', id: 409203825
mas "iA Writer", id: 775737590
