tap 'caskroom/cask'
tap 'github/bootstrap'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dev-tools'
tap 'homebrew/portable'
tap 'homebrew/services'
tap 'homebrew/versions'
tap 'homebrew/homebrew-php'
cask 'java'
brew 'ack'
brew 'autoconf'
brew 'autojump'
brew 'cmake'
brew 'xz'
brew 'libpng'
brew 'freetype'
brew 'gettext'
brew 'pcre'
brew 'git'
brew 'pkg-config'
brew 'libffi'
brew 'glib'
brew 'grc'
brew 'hub'
brew 'libtool'
brew 'jpeg'
brew 'libtiff'
brew 'imagemagick'
brew 'oniguruma'
brew 'jq'
brew 'launch_socket_server', service_restart: true
brew 'launchdns', service_restart: true
brew 'openssl'
brew 'libevent'
brew 'libgpg-error'
brew 'libgcrypt'
brew 'readline'
brew 'sqlite'
brew 'libgda'
brew 'libssh2'
brew 'libgit2'
brew 'mas'
brew 'memcached', service_restart: true
brew 'nginx', service_restart: true
brew 'ruby-build'
brew 'rbenv'
brew 'rbenv-default-gems'
brew 'rbenv-readline'
brew 'nodenv'
brew 'libmcrypt'
brew 'redis', service_restart: true
brew 'shellcheck'
brew 'ssh-copy-id'
brew 'wget'
brew 'homebrew/versions/mysql56'
brew 'homebrew/versions/ruby187'
brew 'php54'
brew 'mongodb'
cask 'appcleaner'
cask 'atom'
cask 'cyberduck'
cask 'firefox'
cask 'github-desktop'
cask 'google-chrome'
cask 'keepingyouawake'
cask 'opera'
cask 'sequel-pro'
cask 'skype'
cask 'spotify'
cask 'vagrant'
cask 'virtualbox'
cask 'xquartz'
mas 'Remote Desktop', id: 409907375
mas 'Xcode', id: 497799835
mas 'Keynote', id: 409183694
mas 'iMovie', id: 408981434
mas 'Slack', id: 803453959
mas 'Pages', id: 409201541
mas 'Pixelmator', id: 407963104
mas 'Numbers', id: 409203825
