#!/bin/bash
set -e

if ! [ -L ~/.gnupg ]
then
  echo "Run script/setup first!" >&2
  exit 1
fi

onepassword_login() {
  if ! command -v op >/dev/null
  then
    echo "Install op first!" >&2
    exit 1
  fi

  # shellcheck disable=SC2154
  if [ -z "$OP_SESSION_my" ]
  then
    echo "Logging into 1Password..."
    eval "$(op signin my.1password.com thompson.glowe@gmail.com)"
  fi
}

onepassword_get() {
  if [ -f "$HOME/$2" ]
  then
    echo "$2 already exists."
    return
  fi
  echo "Extracting $2..."
  onepassword_login
  op get document "$1" > "$HOME/$2"
  chmod 600 "$HOME/$2"
}

onepassword_get j77q43hm7bemddbuo3umhgokee .gnupg/thompson.glowe@gmail.com.private.gpg-key

echo "Setting up GPG..."
if ! command -v gpg >/dev/null
then
    echo "Install GPG first!" >&2
    exit 1
fi

chmod 700 ~/.gnupg
gpg --import ~/.gnupg/thompson.glowe@gmail.com.public.gpg-key \
             ~/.gnupg/thompson.glowe@gmail.com.private.gpg-key